baseurl = "https://frank.gerastree.at/"
title = "Andrew U. Frank"
copyright = "Copyright &copy; 2017 - Andrew U. Frank"
#canonifyurls = true
languageCode = "en-us"
theme = "kiera"
#theme = "lithium"


paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = ""
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "A Hugo theme for creative and technical writing"
    description = "description"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"
    

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:title/"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 1 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Publications"
    weight = 3
    url = "/publications/"